[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
rootDirectory = "."

[variables]
ENVIRONMENT = "production"
DEBUG = "false"
API_V1_STR = "/api/v1"
BACKEND_CORS_ORIGINS = "*"
RATE_LIMIT_PER_MINUTE = "60"
DATABASE_URL = "${{Postgres.DATABASE_URL}}" 