[build]
# Use direct Dockerfile build (recommended for GitHub users)
builder = "DOCKERFILE"
dockerfilePath = "backend/auth_service_v2/Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
startCommand = "python -m alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[service]
rootDirectory = "backend/auth_service_v2" 