[build]
# Trigger rebuild - Database connection configured
builder = "dockerfile"
buildCommand = "pip install -e . && pip install -r requirements.txt"
buildDirectory = "backend/auth_service_v2"
dockerfilePath = "Dockerfile"
watchPatterns = ["/"]

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 60  # Reduced from 300 to fail faster if unhealthy
restartPolicyType = "on_failure"
healthcheckInterval = 15  # Reduced from 45 to check more frequently
restartPolicyMaxRetries = 3  # Reduced from 5 to fail faster
numReplicas = 1  # Ensure only one instance runs at a time

[deploy.envVars]
ENVIRONMENT = "production"
DEBUG = "false"
USE_SYNC_DRIVER = "true"
DEPLOYMENT_ID = "${RAILWAY_DEPLOYMENT_ID}"  # Track unique deployment ID

# Database configuration
DATABASE_URL = "${DATABASE_URL}"
POSTGRES_SERVER = "monorail.proxy.rlwy.net"
POSTGRES_USER = "${POSTGRES_USER}"
POSTGRES_PASSWORD = "${POSTGRES_PASSWORD}"
POSTGRES_DB = "${POSTGRES_DB}"
POSTGRES_PORT = "29421"

# API configuration
API_V1_STR = "/api/v1"
PROJECT_NAME = "auth_service_v2"

# Security
SECRET_KEY = "${SECRET_KEY}"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
REFRESH_TOKEN_EXPIRE_MINUTES = "10080"  # 7 days

# CORS configuration
BACKEND_CORS_ORIGINS = "*"

# Email configuration
SMTP_TLS = "true"
SMTP_PORT = "587"
SMTP_HOST = "smtp.gmail.com"
SMTP_USER = "${SMTP_USER}"
SMTP_PASSWORD = "${SMTP_PASSWORD}"
EMAILS_FROM_EMAIL = "${EMAILS_FROM_EMAIL}"
EMAILS_FROM_NAME = "${PROJECT_NAME}"

# Connection pool settings - Adjusted for multiple deployments
POOL_SIZE = "3"  # Reduced from 5 to prevent connection exhaustion
MAX_OVERFLOW = "5"  # Reduced from 10
POOL_TIMEOUT = "10"  # Reduced from 30 to fail faster
POOL_RECYCLE = "300"  # Reduced from 1800 to recycle connections more frequently
ECHO_SQL = "false"

# Deployment settings
STARTUP_GRACE_PERIOD = "30"  # Grace period in seconds before health checks start
MAX_DEPLOYMENT_TIME = "180"  # Maximum time in seconds for deployment to complete

# Temporarily removed health check config
# healthcheckPath = "/api/v1/health"
# healthcheckTimeout = 300
# healthcheckInterval = 45 