[build]
# Trigger rebuild - Database connection configured
builder = "dockerfile"
buildCommand = "pip install -e . && pip install -r requirements.txt"
buildDirectory = "backend/auth_service_v2"
dockerfilePath = "Dockerfile"
watchPatterns = ["/"]

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
healthcheckInterval = 45
restartPolicyMaxRetries = 5

[deploy.envVars]
ENVIRONMENT = "production"
DEBUG = "false"
USE_SYNC_DRIVER = "true"

# Database configuration
DATABASE_URL = "${DATABASE_URL}"
POSTGRES_SERVER = "postgres.railway.internal"
POSTGRES_USER = "${POSTGRES_USER}"
POSTGRES_PASSWORD = "${POSTGRES_PASSWORD}"
POSTGRES_DB = "${POSTGRES_DB}"
POSTGRES_PORT = "5432"

# API configuration
API_V1_STR = "/api/v1"
PROJECT_NAME = "auth_service_v2"

# Security
SECRET_KEY = "${SECRET_KEY}"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
REFRESH_TOKEN_EXPIRE_MINUTES = "10080"  # 7 days

# CORS configuration
BACKEND_CORS_ORIGINS = "*"

# Email configuration
SMTP_TLS = "true"
SMTP_PORT = "587"
SMTP_HOST = "smtp.gmail.com"
SMTP_USER = "${SMTP_USER}"
SMTP_PASSWORD = "${SMTP_PASSWORD}"
EMAILS_FROM_EMAIL = "${EMAILS_FROM_EMAIL}"
EMAILS_FROM_NAME = "${PROJECT_NAME}"

# Connection pool settings
POOL_SIZE = "5"
MAX_OVERFLOW = "10"
POOL_TIMEOUT = "30"
POOL_RECYCLE = "1800"
ECHO_SQL = "false"

# Temporarily removed health check config
# healthcheckPath = "/api/v1/health"
# healthcheckTimeout = 300
# healthcheckInterval = 45 