[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
NO_CACHE = "1"

[deploy]
startCommand = "sleep 15 && python -m alembic upgrade head && PYTHONUNBUFFERED=1 LOG_LEVEL=debug UVICORN_WORKERS=1 python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1 --log-level debug --timeout-keep-alive 120"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
healthcheckInterval = 30
restartPolicyMaxRetries = 3

[deploy.env]
ENVIRONMENT = "production"
DEBUG = "true"  # Temporarily enable debug for better error logging 