the old auth component
name: Auth Service CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/auth_service_v2/**'
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        working-directory: ./backend/auth_service_v2
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      - name: Run tests
        working-directory: ./backend/auth_service_v2
        run: |
          pytest
        env:
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ENVIRONMENT: test 