name: Test Deployed Services

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  test-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run deployment tests
        run: |
          python test_deployment.py
        env:
          AUTH_SERVICE_URL: ${{ secrets.AUTH_SERVICE_URL }}
          USER_SERVICE_URL: ${{ secrets.USER_SERVICE_URL }} 